# Generated by Django 6.0.2 on 2026-02-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="q_type",
            field=models.CharField(
                choices=[("objective", "客观题"), ("subjective", "主观题")],
                default="objective",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="is_initial_placement",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(blank=True, help_text="客观题标准答案或主观题参考答案", null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(blank=True, help_text="客观题选项", null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="题目内容"),
        ),
    ]
