# Generated by Django 6.0.2 on 2026-02-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_userquestionstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="ai_answer",
            field=models.TextField(blank=True, null=True, verbose_name="AI 生成的深度解析答案"),
        ),
        migrations.AddField(
            model_name="question",
            name="grading_points",
            field=models.TextField(blank=True, help_text="得分点说明（主观题必填）", null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="subjective_type",
            field=models.CharField(
                blank=True,
                choices=[("noun", "名词解释"), ("short", "简答题"), ("essay", "论述题")],
                max_length=20,
                null=True,
                verbose_name="主观题类型",
            ),
        ),
    ]
