# Generated by Django 6.0.2 on 2026-02-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0004_question_ai_answer_question_grading_points_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="知识点名称")),
                ("description", models.TextField(blank=True, verbose_name="知识点描述")),
                (
                    "structural_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="存放通用的结构化数据，如公式库、背景资料等"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="是否收藏"),
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="wrong_count",
            field=models.IntegerField(default=0, verbose_name="错误次数"),
        ),
        migrations.AddField(
            model_name="question",
            name="knowledge_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="quizzes.knowledgepoint",
            ),
        ),
    ]
