# Generated by Django 6.0.2 on 2026-02-16 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0005_knowledgepoint_userquestionstatus_is_favorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgepoint",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="quizzes.knowledgepoint",
                verbose_name="上级知识点",
            ),
        ),
    ]
