# Generated by Django 6.0.2 on 2026-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0006_knowledgepoint_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="subjective_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("noun", "名词解释"),
                    ("short", "简答题"),
                    ("essay", "论述题"),
                    ("calculate", "计算题"),
                ],
                max_length=20,
                null=True,
                verbose_name="主观题类型",
            ),
        ),
    ]
