# Generated by Django 6.0.2 on 2026-02-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0007_alter_question_subjective_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquestionstatus",
            name="review_stage",
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="difficulty",
            field=models.FloatField(default=0.0, help_text="记忆难度 (D)，范围 1-10"),
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="lapses",
            field=models.IntegerField(default=0, help_text="忘记次数"),
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="last_review",
            field=models.DateTimeField(blank=True, help_text="上次复习时间", null=True),
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="reps",
            field=models.IntegerField(default=0, help_text="总复习次数"),
        ),
        migrations.AddField(
            model_name="userquestionstatus",
            name="stability",
            field=models.FloatField(default=0.0, help_text="记忆稳定性 (S)，单位：天"),
        ),
    ]
