# Generated by Django 6.0.2 on 2026-02-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0009_quizexam_examquestionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionstatus",
            name="is_mastered",
            field=models.BooleanField(default=False, verbose_name="是否已掌握(排除)"),
        ),
    ]
