# Generated by Django 6.0.2 on 2026-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0010_userquestionstatus_is_mastered"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("entry", "入门 (Entry)"),
                    ("easy", "简单 (Easy)"),
                    ("normal", "适当 (Normal)"),
                    ("hard", "困难 (Hard)"),
                    ("extreme", "极限 (Extreme)"),
                ],
                default="normal",
                max_length=20,
                verbose_name="难度等级",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(default=1200, help_text="基准 ELO 分值"),
        ),
    ]
