# Generated by Django 6.0.2 on 2026-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0011_question_difficulty_level_alter_question_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgepoint",
            name="structural_data",
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="唯一编码(如MB-1001)"
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="level",
            field=models.CharField(
                choices=[
                    ("sub", "模块(SUB)"),
                    ("ch", "篇章(CH)"),
                    ("sec", "小节(SEC)"),
                    ("kp", "考点(KP)"),
                ],
                default="kp",
                max_length=10,
                verbose_name="层级",
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="prefix_category",
            field=models.CharField(
                blank=True,
                help_text="如 MB, IF, CF 等",
                max_length=20,
                null=True,
                verbose_name="学科前缀",
            ),
        ),
    ]
