# Generated by Django 6.0.2 on 2026-02-26 16:14

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations, models


class SafeRemoveField(migrations.RemoveField):
    """
    Some environments already lost the field in migration state due to history drift.
    Skip safely when the field is absent; remove normally when it exists.
    """

    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except KeyError:
            # Field is already absent in historical state.
            return

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        try:
            field = model._meta.get_field(self.name)
        except FieldDoesNotExist:
            return

        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = {
                col.name
                for col in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }
        if field.column in columns:
            schema_editor.remove_field(model, field)


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0011_question_difficulty_level_alter_question_difficulty"),
    ]

    operations = [
        SafeRemoveField(
            model_name="knowledgepoint",
            name="structural_data",
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="唯一编码(如MB-1001)"
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="level",
            field=models.CharField(
                choices=[
                    ("sub", "模块(SUB)"),
                    ("ch", "篇章(CH)"),
                    ("sec", "小节(SEC)"),
                    ("kp", "考点(KP)"),
                ],
                default="kp",
                max_length=10,
                verbose_name="层级",
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="prefix_category",
            field=models.CharField(
                blank=True,
                help_text="如 MB, IF, CF 等",
                max_length=20,
                null=True,
                verbose_name="学科前缀",
            ),
        ),
    ]
