# Generated by Django 6.0.2 on 2026-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0002_bot_aichatmessage_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="is_exclusive",
            field=models.BooleanField(default=False, verbose_name="是否为专属导师"),
        ),
    ]
