# Generated by Django 6.0.2 on 2026-02-22 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq_system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关注者",
            ),
        ),
    ]
