# Generated by Django 6.0.2 on 2026-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(help_text="支持 Markdown 和 LaTeX 格式"),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="article_covers/"),
        ),
    ]
