# Generated by Django 6.0.2 on 2026-02-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_content_alter_article_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_display_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="发布人名称"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.JSONField(blank=True, default=list, help_text="文章标签列表"),
        ),
    ]
