# Generated by Django 6.0.2 on 2026-02-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_author_display_name_article_tags"),
        ("quizzes", "0006_knowledgepoint_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="knowledge_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="quizzes.knowledgepoint",
                verbose_name="挂载知识点",
            ),
        ),
    ]
