# Generated by Django 6.0.2 on 2026-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_knowledge_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="阅读量"),
        ),
    ]
