# Generated by Django 6.0.2 on 2026-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="video_url",
        ),
        migrations.AddField(
            model_name="course",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="course_videos/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_covers/"),
        ),
    ]
