# Generated by Django 6.0.2 on 2026-02-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_course_video_url_course_video_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="courseware",
            field=models.FileField(
                blank=True, null=True, upload_to="courseware/", verbose_name="课件"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="reference_materials",
            field=models.FileField(
                blank=True, null=True, upload_to="references/", verbose_name="参考资料"
            ),
        ),
    ]
