# Generated by Django 6.0.2 on 2026-02-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_courseware_course_reference_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="album",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="所属专辑/系列"
            ),
        ),
    ]
