# Generated by Django 6.0.2 on 2026-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="elo_reward",
            field=models.IntegerField(default=50, verbose_name="观看完成奖励 ELO"),
        ),
    ]
