# Generated by Django 6.0.2 on 2026-02-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_course_elo_reward"),
        ("quizzes", "0006_knowledgepoint_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="专辑名称")),
                ("description", models.TextField(blank=True, verbose_name="专辑描述")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="album_covers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="knowledge_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="quizzes.knowledgepoint",
                verbose_name="挂载知识点",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="album",
            field=models.CharField(
                blank=True, help_text="保留旧字段兼容", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="album_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.album",
                verbose_name="所属专辑",
            ),
        ),
    ]
