# Generated by Django 6.0.2 on 2026-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_album_course_knowledge_point_alter_course_album_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="资料名称")),
                ("description", models.TextField(blank=True, verbose_name="资料简介")),
                (
                    "file",
                    models.FileField(upload_to="startup_materials/", verbose_name="文件"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
