# Generated by Django 6.0.2 on 2026-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_videoprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="album",
        ),
    ]
