# Generated by Django 6.0.2 on 2026-02-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study_room", "0001_initial"),
        ("users", "0011_dailyplan_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="related_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcast_messages",
                to="users.dailyplan",
            ),
        ),
    ]
