# Generated by Django 6.0.2 on 2026-02-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_systemconfig_user_avatar_seed_user_avatar_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
