# Generated by Django 6.0.2 on 2026-02-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_avatar_options_user_is_online_user_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_task",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_timer_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
