# Generated by Django 6.0.2 on 2026-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_today_completed_tasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="elo_reset_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="has_completed_initial_assessment",
            field=models.BooleanField(default=False),
        ),
    ]
