# Generated by Django 6.0.2 on 2026-02-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_elo_reset_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="school_logo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
