# Generated by Django 6.0.2 on 2026-02-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_systemconfig_school_logo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemconfig",
            name="school_logo_url",
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="school_logo",
            field=models.ImageField(blank=True, null=True, upload_to="school_logos/"),
        ),
    ]
