# Generated by Django 6.0.2 on 2026-02-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_systemconfig_school_logo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="school_short_name",
            field=models.CharField(default="知行", max_length=20, verbose_name="网校缩写"),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_broadcast",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_others_broadcast",
            field=models.BooleanField(default=True),
        ),
    ]
