# Generated by Django 6.0.2 on 2026-02-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_systemconfig_school_short_name_user_allow_broadcast_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="invite_code",
            field=models.CharField(
                default="KORSON2025", max_length=50, verbose_name="邀请码"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, verbose_name="昵称"),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="school_description",
            field=models.TextField(default="KORSON ACADEMY"),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="school_name",
            field=models.CharField(default="科晟智慧", max_length=100),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="school_short_name",
            field=models.CharField(default="科晟", max_length=20, verbose_name="网校缩写"),
        ),
    ]
