# Generated by Django 6.0.2 on 2026-02-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_systemconfig_invite_code_user_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplan",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
