# Generated by Django 6.0.2 on 2026-02-23 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_dailyplan_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_member",
            field=models.BooleanField(default=False, verbose_name="是否会员"),
        ),
        migrations.CreateModel(
            name="ActivationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="激活码"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="是否已使用")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
