# Generated by Django 6.0.2 on 2026-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_is_member_activationcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_options",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_online",
        ),
    ]
