# Generated by Django 6.0.2 on 2026-02-26 16:14

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations


class SafeRemoveField(migrations.RemoveField):
    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except KeyError:
            return

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        try:
            field = model._meta.get_field(self.name)
        except FieldDoesNotExist:
            return

        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = {
                col.name
                for col in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }
        if field.column in columns:
            schema_editor.remove_field(model, field)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_is_member_activationcode"),
    ]

    operations = [
        SafeRemoveField(
            model_name="user",
            name="avatar_options",
        ),
        SafeRemoveField(
            model_name="user",
            name="avatar_url",
        ),
        SafeRemoveField(
            model_name="user",
            name="is_online",
        ),
    ]
